
export const CONSTANT = Object.freeze({
    LICENSE_TYPE: {
        TERMS_AND_CONDITIONS: 'TERMS_N_CONDITIONS',
        PRIVATE_POLICY: 'PRIVACY_POLICY'
    },
    TITLE: {
        TERMS_AND_CONDITIONS: 'Terms And Conditions',
        PRIVATE_POLICY: 'Private Policy'
    },
    TOAST_TIMEOUT: 5000,
    GDPR_PATH: '/system-manager/sv/gdpr'
});

export const PermissionEnum = {
    DATACHANGE_COPY_VIEW: "DATACHANGE_COPY_VIEW",
    DATACHANGE_EXPORT_EXCEL_VIEW: "DATACHANGE_EXPORT_EXCEL_VIEW",
    DATACHANGE_EXPORT_PDF_VIEW: "DATACHANGE_EXPORT_PDF_VIEW",
    DATACHANGE_PRINT_VIEW: "DATACHANGE_PRINT_VIEW",
    DATACHANGE_SEARCH_VIEW: "DATACHANGE_SEARCH_VIEW", 
    DATACHANGE_DATE_FROM_FILTER_VIEW: "DATACHANGE_DATE_FROM_FILTER_VIEW",
    DATACHANGE_DATE_TO_FILTER_VIEW: "DATACHANGE_DATE_TO_FILTER_VIEW",
    DATACHANGE_UPDATE_BY_FILTER_VIEW: "DATACHANGE_UPDATE_BY_FILTER_VIEW",
    DATACHANGE_FIELD_NAME_FILTER_VIEW: "DATACHANGE_FIELD_NAME_FILTER_VIEW",
};